version: '3.3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES-USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES-DB=db_name
    ports:
      - 5436:5432
